import { getOctokit, rateLimitedRequest } from "../github-client.js";
import { loadContributions, getMetrics } from "../submit/track.js";

export async function sendDailySummary() {
  const octokit = getOctokit();
  const contributions = loadContributions();
  const metrics = getMetrics(contributions);

  // Get today's contributions
  const today = new Date().toISOString().split("T")[0];
  const todaysContributions = contributions.filter(
    (c) => c.timestamp && c.timestamp.startsWith(today)
  );

  const title = `Daily Report: ${today} — ${todaysContributions.length} PR(s) submitted`;
  const body = buildSummaryBody(todaysContributions, metrics, today);

  // Get authenticated user to find the repo
  const { data: user } = await octokit.users.getAuthenticated();

  try {
    const { data: issue } = await rateLimitedRequest(() =>
      octokit.issues.create({
        owner: user.login,
        repo: "auto-oss-contributor",
        title,
        body,
        labels: ["daily-report"],
      })
    );

    console.log(`Daily summary posted: ${issue.html_url}`);
    return issue.html_url;
  } catch (error) {
    console.warn(`Failed to post daily summary: ${error.message}`);
    return null;
  }
}

function buildSummaryBody(todaysContributions, metrics, today) {
  let body = `# Daily Contribution Report — ${today}\n\n`;

  if (todaysContributions.length === 0) {
    body += `> No PRs were submitted today. This could mean:\n`;
    body += `> - No issues passed the quality gate (confidence < threshold)\n`;
    body += `> - No repos matched the etiquette filters\n`;
    body += `> - API rate limits were hit\n\n`;
  } else {
    body += `## Today's Contributions\n\n`;
    body += `| # | Repo | Issue | PR | Type | Confidence |\n`;
    body += `|---|------|-------|----|------|------------|\n`;

    todaysContributions.forEach((c, i) => {
      body += `| ${i + 1} | ${c.repoFullName || "N/A"} | [#${c.issueNumber || "?"}](${c.issueUrl || "#"}) | [PR #${c.prNumber || "?"}](${c.prUrl || "#"}) | ${c.type || "N/A"} | ${(c.confidence * 100).toFixed(0)}% |\n`;
    });
  }

  body += `\n## Overall Stats\n\n`;
  body += `| Metric | Value |\n`;
  body += `|--------|-------|\n`;
  body += `| Total PRs (all time) | ${metrics.total} |\n`;
  body += `| Merged | ${metrics.merged} |\n`;
  body += `| Open | ${metrics.open} |\n`;
  body += `| Closed/Rejected | ${metrics.closed} |\n`;
  body += `| Merge Rate | ${metrics.mergeRate}% |\n`;

  if (Object.keys(metrics.byLanguage).length > 0) {
    body += `\n## Languages\n\n`;
    for (const [lang, count] of Object.entries(metrics.byLanguage).sort((a, b) => b[1] - a[1])) {
      body += `- **${lang}**: ${count} PR(s)\n`;
    }
  }

  if (Object.keys(metrics.byType).length > 0) {
    body += `\n## Contribution Types\n\n`;
    for (const [type, count] of Object.entries(metrics.byType).sort((a, b) => b[1] - a[1])) {
      body += `- **${type}**: ${count} PR(s)\n`;
    }
  }

  body += `\n---\n*Auto-generated by [Auto OSS Contributor](https://github.com/NoBuddy-Stack/auto-oss-contributor)*`;

  return body;
}
