import { execFileSync } from "child_process";
import { writeFileSync } from "fs";
import { join } from "path";
import { getOctokit, rateLimitedRequest } from "../github-client.js";
import { getPRTemplate } from "../analyze/guidelines.js";

export async function submitPR(analysis, changes, repoDir, fork, contributingGuide) {
  const { issue, type } = analysis;
  const octokit = getOctokit();

  // Create branch name
  const branchName = `fix/issue-${issue.number}-${type}-${Date.now()}`;

  console.log(`Creating branch ${branchName} on fork ${fork.owner}/${fork.repo}...`);

  // Apply changes to repo
  for (const change of changes) {
    const filePath = join(repoDir, change.path);
    writeFileSync(filePath, change.content, "utf-8");
  }

  // Configure git for the temp repo
  execFileSync("git", ["config", "user.email", "auto-oss-contributor@users.noreply.github.com"], { cwd: repoDir });
  execFileSync("git", ["config", "user.name", "Auto OSS Contributor"], { cwd: repoDir });

  // Create branch, stage, and commit
  execFileSync("git", ["checkout", "-b", branchName], { cwd: repoDir });
  execFileSync("git", ["add", "."], { cwd: repoDir });

  const commitMessage = generateCommitMessage(issue, type, contributingGuide);
  execFileSync("git", ["commit", "-m", commitMessage], { cwd: repoDir, stdio: "pipe" });

  // Push to fork
  const pushUrl = `https://x-access-token:${process.env.GITHUB_PAT}@github.com/${fork.owner}/${fork.repo}.git`;
  execFileSync("git", ["remote", "set-url", "origin", pushUrl], { cwd: repoDir });
  execFileSync("git", ["push", "-u", "origin", branchName], { cwd: repoDir, stdio: "pipe" });

  // Create PR
  const prBody = await buildPRBody(issue, type, changes, contributingGuide);
  const defaultBranch = await getDefaultBranch(issue.repoOwner, issue.repoName);

  const { data: pr } = await rateLimitedRequest(() =>
    octokit.pulls.create({
      owner: issue.repoOwner,
      repo: issue.repoName,
      title: generatePRTitle(issue, type),
      body: prBody,
      head: `${fork.owner}:${branchName}`,
      base: defaultBranch,
    })
  );

  console.log(`PR created: ${pr.html_url}`);
  return {
    url: pr.html_url,
    number: pr.number,
    title: pr.title,
    branch: branchName,
  };
}

function generateCommitMessage(issue, type, guide) {
  const prefixes = {
    typo: "fix",
    docs: "docs",
    bug: "fix",
    test: "test",
    feature: "feat",
    dependency: "chore",
  };
  const prefix = prefixes[type] || "fix";

  // Check if repo uses conventional commits
  if (guide?.commitFormat?.toLowerCase().includes("conventional")) {
    return `${prefix}: ${issue.title}\n\nFixes #${issue.number}`;
  }

  return `${issue.title}\n\nFixes #${issue.number}`;
}

function generatePRTitle(issue, type) {
  const prefixes = {
    typo: "Fix typo:",
    docs: "Docs:",
    bug: "Fix:",
    test: "Add tests:",
    feature: "Feat:",
    dependency: "Chore: Update",
  };
  const prefix = prefixes[type] || "Fix:";
  return `${prefix} ${issue.title}`.slice(0, 100);
}

async function buildPRBody(issue, type, changes, guide) {
  // Check for PR template
  let template = null;
  try {
    template = await getPRTemplate(issue.repoOwner, issue.repoName);
  } catch {
    // No template
  }

  const filesChanged = changes.map((c) => `- \`${c.path}\` (${c.action})`).join("\n");

  let body = `## Summary

This PR addresses #${issue.number}.

**Type:** ${type}

## Changes

${filesChanged}

## Context

${issue.body?.slice(0, 500) || "See linked issue for details."}

---
*This contribution was automatically generated by [Auto OSS Contributor](https://github.com/auto-oss-contributor).*`;

  return body;
}

async function getDefaultBranch(owner, repo) {
  const octokit = getOctokit();
  const { data } = await rateLimitedRequest(() =>
    octokit.repos.get({ owner, repo })
  );
  return data.default_branch;
}
